"""One-dimensional, two-temperature reacting plug flow through a catalyst bed.

Formulation
-----------
Steady flow along the bed axis ``z``, with the gas and the catalyst carrying
*separate* temperatures. Reactions happen on the solid, so the rates see the
catalyst temperature, while the gas is heated by convection from it. In the
decomposition zone the solid runs hot; where ammonia dissociation dominates
it can run cold, because that reaction absorbs heat.

The gas equations are::

    G dY_i/dz = omega_i                  species
    G dh/dz   = -q_loss                  energy
      dp/dz   = -(Ergun)                 momentum

with ``G`` the superficial mass flux. Note what the energy equation is *not*:
there is no reaction source term in it. For an adiabatic bed the reaction
enthalpy is already carried by the species enthalpies, so total enthalpy is
simply conserved and ``h`` is constant. That is worth stating because it makes
a strong internal check available -- the plug-flow exit temperature must equal
the closed-form adiabatic temperature at the same dissociation fraction, and a
test asserts it.

The solid temperature is not integrated. It follows from a local balance
between heat generated by reaction and heat handed to the gas::

    Q_reaction(T_s) = h_c a_v (T_s - T_g)

which is solved by bracketing at every station. It is genuinely two-sided:
exothermic decomposition drives ``T_s`` above ``T_g``, endothermic
dissociation drives it below.

Heat transfer uses the Chilton-Colburn analogy applied to Kesten's own mass
transfer correlation, so the two are consistent by construction::

    h_c = 0.61 G cp Pr^-0.667 [G/(a_v mu)]^-0.41

Where the model starts
----------------------
The bed is fed *liquid*, and vaporisation is not modelled: the integration
begins at the vapour-region inlet, with a composition and temperature you
supply. This matters more than it might seem. Starting from pure cold
hydrazine vapour is not merely an approximation, it is unusable -- conserving
enthalpy through instantaneous vaporisation puts the vapour below the feed
temperature, Arrhenius rates go to zero and nothing ever ignites. Real beds
solve this by conducting heat upstream from the hot zone, which a
one-dimensional steady model cannot represent.

Kesten handles it with explicit liquid and liquid-vapour regions, and his
vapour region begins at 820 degR already ~55% decomposed. Supplying that state
as the inlet is how this model is validated against his.
"""
import numpy as np
from scipy.integrate import solve_ivp
from scipy.optimize import brentq

from . import chem


class PlugFlowSolution:
    """Profiles along the bed, plus the derived quantities worth having."""

    def __init__(self, reactor, z, Y, h, p, T_gas, T_solid, rates):
        self.reactor = reactor
        self.z = z
        self.Y = Y                      # (n_species, n_points)
        self.h = h
        self.p = p
        self.T_gas = T_gas
        self.T_solid = T_solid
        self.rates = rates              # (n_reactions, n_points)
        self.mixture = reactor.mechanism.mixture

    def species(self, name):
        return self.Y[self.mixture.index(name)]

    @property
    def mole_fractions(self):
        return self.mixture.mole_fractions(self.Y)

    @property
    def MW(self):
        return self.mixture.MW(self.Y)

    @property
    def rho(self):
        return self.p / (self.mixture.R(self.Y) * self.T_gas)

    @property
    def dissociation(self):
        """Ammonia dissociation fraction X, in the two-step convention.

        Recovered from the element balance rather than tracked, so it stays
        meaningful part-way through the bed where hydrazine remains.

        The normalisation is by ammonia *produced*, not ammonia that would
        exist if all the hydrazine had decomposed. Dividing by the latter
        conflates "not yet formed" with "already dissociated" and reads 0.71
        at Kesten's vapour-region inlet where the true value is 0.25. With the
        correct denominator this reproduces his reported fraction to five
        decimals at every station.
        """
        x = self.mole_fractions
        m = self.mixture
        n4 = x[m.index("N2H4")]
        n3 = x[m.index("NH3")]
        n2 = x[m.index("N2")]
        fed = n4 + 0.5 * (n3 + 2.0 * n2)          # moles of N2H4 originally
        produced = np.maximum(fed - n4, 1e-30)    # ... that have decomposed
        return 1.0 - 0.75 * n3 / produced

    @property
    def pressure_drop(self):
        return float(self.p[0] - self.p[-1])

    def exit_conditions(self):
        """Chamber conditions handed to the nozzle solver."""
        Y = self.Y[:, -1]
        T = float(self.T_gas[-1])
        MW = float(self.mixture.MW(Y))
        g = float(self.mixture.gamma(T, Y))
        R = chem.RU / MW
        cstar = np.sqrt(g * R * T) / (
            g * np.sqrt((2.0 / (g + 1.0)) ** ((g + 1.0) / (g - 1.0))))
        return dict(T=T, p=float(self.p[-1]), MW=MW, gamma=g, R=R,
                    cstar=float(cstar), Y=Y,
                    dissociation=float(self.dissociation[-1]))

    def summary(self):
        e = self.exit_conditions()
        L = ["Plug-flow solution",
             f"  bed length          {self.z[-1] * 1e3:8.2f} mm",
             f"  gas temperature     {self.T_gas[0]:8.1f} -> {self.T_gas[-1]:8.1f} K",
             f"  solid temperature   {self.T_solid[0]:8.1f} -> {self.T_solid[-1]:8.1f} K",
             f"  pressure            {self.p[0] / 6894.757:8.2f} -> "
             f"{self.p[-1] / 6894.757:8.2f} psia",
             f"  dissociation X      {self.dissociation[0]:8.3f} -> "
             f"{self.dissociation[-1]:8.3f}",
             f"  exit MW             {e['MW']:8.3f} kg/kmol",
             f"  exit gamma          {e['gamma']:8.4f}",
             f"  exit c*             {e['cstar']:8.1f} m/s"]
        return "\n".join(L)


class PlugFlowReactor:
    """Integrates the bed equations for a given mechanism and packing.

    Parameters
    ----------
    mechanism : Mechanism
    bed : CatalystBed
    Pr : float
        Prandtl number used in the heat-transfer analogy.
    q_loss : float or callable
        Volumetric heat loss [W/m^3]; 0 gives an adiabatic bed.
    """

    def __init__(self, mechanism, bed, Pr=0.7, q_loss=0.0):
        self.mechanism = mechanism
        self.bed = bed
        self.Pr = float(Pr)
        self.q_loss = q_loss

    # -- closures ---------------------------------------------------------
    def heat_transfer_coefficient(self, G, cp, mu, medium):
        """``h_c`` [W/(m^2 K)] by Chilton-Colburn from Kesten's ``KCF``."""
        Re_a = np.maximum(G / (medium.a_v * np.maximum(mu, 1e-12)), 1e-12)
        return 0.61 * G * cp * self.Pr ** -0.667 * Re_a ** -0.41

    def solid_temperature(self, T_gas, p, Y, G, medium, span=2500.0, tol=1e-3):
        """Solve ``Q_rxn(T_s) = h_c a_v (T_s - T_g)`` for the catalyst temperature.

        Bracketed rather than Newton-solved: the reaction term is a sum of
        Arrhenius exponentials with opposite signs, so the residual is not
        reliably monotone and a derivative-based method can walk off it.
        """
        mech = self.mechanism
        mu = mech.viscosity(T_gas, Y)
        cp = mech.mixture.cp(T_gas, Y)
        hc = self.heat_transfer_coefficient(G, cp, mu, medium)
        coupling = hc * medium.a_v

        def residual(T_s):
            r = mech.rates(T_gas, T_s, p, Y, G, medium, mu=mu)
            return mech.heat_release(T_s, r) - coupling * (T_s - T_gas)

        lo, hi = T_gas - span, T_gas + span
        lo = max(lo, 200.0)
        f_lo, f_hi = residual(lo), residual(hi)
        if f_lo * f_hi > 0.0:
            # No sign change: the exchange term dominates everywhere, which
            # means the solid is essentially at the gas temperature.
            return T_gas if abs(f_lo) < abs(f_hi) else hi
        # Brent rather than bisection. The bracket is wide (T_gas +/- 2500 K)
        # so bisection needed ~24 evaluations to reach tolerance, and each one
        # costs a full rate and heat-release evaluation -- it dominated the
        # profile. Brent gets there in roughly a third of that.
        return float(brentq(residual, lo, hi, xtol=tol, rtol=1e-10,
                            maxiter=60, disp=False))

    # -- right-hand side --------------------------------------------------
    def _unpack(self, z, state, G):
        n = self.mechanism.mixture.n
        Y = np.maximum(state[:n], 0.0)
        s = Y.sum()
        Y = Y / s if s > 0 else self.mechanism.inlet_composition()
        h, p = state[n], max(state[n + 1], 1.0)
        T_gas = float(self.mechanism.mixture.temperature_from_h(h, Y, T_guess=900.0))
        medium = self.bed.medium_at(z)
        T_solid = self.solid_temperature(T_gas, p, Y, G, medium)
        return Y, h, p, T_gas, T_solid, medium

    def rhs(self, z, state, G):
        mech = self.mechanism
        Y, h, p, T_gas, T_solid, medium = self._unpack(z, state, G)

        r = mech.rates(T_gas, T_solid, p, Y, G, medium)
        omega = mech.production_rates(r)

        rho = p / (mech.mixture.R(Y) * T_gas)
        mu = mech.viscosity(T_gas, Y)
        dpdz = -medium.pressure_gradient(G, rho, mu)

        q = self.q_loss(z) if callable(self.q_loss) else self.q_loss
        out = np.empty_like(state)
        out[:mech.mixture.n] = omega / G
        out[mech.mixture.n] = -q / G
        out[mech.mixture.n + 1] = dpdz
        return out

    # -- driver -----------------------------------------------------------
    def solve(self, G, p_inlet, T_inlet, Y_inlet=None, n_output=400,
              rtol=1e-6, atol=1e-9, method="LSODA", max_step=np.inf,
              profiles=True):
        """Integrate from the vapour-region inlet to the bed exit.

        ``T_inlet`` and ``Y_inlet`` describe the state where the vapour region
        begins, not the liquid feed -- see the module docstring.
        """
        mech = self.mechanism
        Y0 = mech.inlet_composition() if Y_inlet is None else \
            mech.mixture.normalized(np.asarray(Y_inlet, dtype=float))
        h0 = float(mech.mixture.h(T_inlet, Y0))

        state0 = np.concatenate([Y0, [h0, float(p_inlet)]])
        z_eval = np.linspace(0.0, self.bed.length, int(n_output))

        sol = solve_ivp(self.rhs, (0.0, self.bed.length), state0,
                        args=(G,), t_eval=z_eval, method=method,
                        rtol=rtol, atol=atol, max_step=max_step, dense_output=False)
        if not sol.success:
            raise RuntimeError(f"plug-flow integration failed: {sol.message}")

        n = mech.mixture.n
        Y = mech.mixture.normalized(np.maximum(sol.y[:n], 0.0))
        h, p = sol.y[n], np.maximum(sol.y[n + 1], 1.0)

        T_gas = np.array([float(mech.mixture.temperature_from_h(
            h[k], Y[:, k], T_guess=900.0)) for k in range(len(sol.t))])
        # Reconstructing the catalyst temperature costs a bracketed solve per
        # station and dominates the run time when only the exit state is
        # wanted, which is the case inside the system-level iteration.
        T_solid = np.full_like(T_gas, np.nan)
        rates = np.full((len(mech.reactions), len(sol.t)), np.nan)
        stations = range(len(sol.t)) if profiles else (len(sol.t) - 1,)
        for k in stations:
            medium = self.bed.medium_at(sol.t[k])
            T_solid[k] = self.solid_temperature(T_gas[k], p[k], Y[:, k], G, medium)
            rates[:, k] = mech.rates(T_gas[k], T_solid[k], p[k], Y[:, k], G, medium)

        return PlugFlowSolution(self, sol.t, Y, h, p, T_gas, T_solid, rates)

    def solve_for_mdot(self, mdot, p_inlet, T_inlet, **kw):
        """Same, taking a mass flow rate instead of a flux."""
        return self.solve(self.bed.mass_flux(mdot), p_inlet, T_inlet, **kw)
