		SUBROUTINE REDIVD (DZ1,DTDZ,NINT,JFLAG,I,LL) 						   0
C		THIS ROUTINE REDIVIDES Z INCREMENTS TO COMPENSATE FOR RADICAL
C		CHANGES IN TEMP,CONCENTRATION,AND OTHER PARAMETERS WHICH OCCUR IN
C		THAT REGION OF THE REACTOR BED FOLLOWING THE TEMPERATURE PEAK
C		THIS ROUTINE IS USED ONLY WHEN INITIAL HYDRAZINE FEED RATE IS NON-
C		ZERO
		INTEGER PRINT														  10
		COMMON /FTZ/TBLVP(70),TBLH4(42),TBLH3(42),SHTBL1(34),SHTBL2(34), 	  20
	   1        SHTBL3(34),SHTBL4(34),ZTBLD(46),ZTBLAP(46),ZTBLA(46) 		  30
		COMMON /CO/HL,HV,FC,TF,CFL,CGM,ENMX1,AGM,DIF3,DIF4,KP,PRES,G0,		  40
	   1        WM4,WM3,WM2,WM1,ALPHA3,R,TVAP,ZEND,BGM,HF,DZ,ALPHA1,ALPHA2	  50
	   2        ,ENMX2,ENMX3,EN1,EN2,EN3,H,RAT,MI 							  60
		COMMON /VAR/DERIV(250),DHDZ(250),Z(250)								  70
		COMMON /TOLL/ALIM,OPTION,C1,C2,C3,C4,CAV,G,TEMP,AP,WMAV,Z0,			  80
		COMMON /MUVST/VISVST(30)											  90
		COMMON /FLAGS/MFLAG,KFLAG,PRINT 									 100
		COMMON /IFCE00/IFC,GATZ0											 110
		I=0 																 120
		NESTCT=1															 130
C		IF A REDIVISION OCCURS WITHIN A PREVIOUS REDIVISION, NESTCT IS USED
C		TO OBTAIN A NEW INTERVAL COUNT
		IF(NINT-1)1,1,2														 140
      2 NESTCT=NINT															 150
	  1 I=I+1																 160
		XSIZE=2.**I															 170
		NINT=XSIZE															 180
		DZ=DZ1/XSIZE														 190
		IF(ABS(DTDZ)*DZ.GT..01*TEMP)GO TO 1									 200
		IF((1.+DZ/(Z(LL)-Z0)+.01*Z0/ABS(Z(LL))-Z0)).LT.0.)GO TO 1			 210
		NINT=NINT*NESTCT													 220
		JFLAG=1																 230
		RETURN																 240
		END																	 250
